In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

# Biblioteca Pandas, series y dataframes

Pandas es una biblioteca de Python muy usada para análisis y manipulación de datos. Provee principalmente dos tipos de clases para trabajar con datos:

- **Series:** un vector unidimensional indexado, que contiene datos de cualquier tipo
como números enteros, cadenas, objetos Python, etc.

- **DataFrame:** una estructura de datos bidimensional que contiene datos como una matriz bidimensional o una tabla con filas y columnas.

Bibliografía recomendada: Sección 5 de Python for Data Analysis, de Wes McKinney (creador de la biblioteca Pandas), disponible on-line en forma gratuita en la página
https://wesmckinney.com/book/pandas-basics

### Series

Las series de Pandas son vectores similares a los arrays de NumPy, que podemos indexar usando etiquetas.

**Ejercicio:** Crear la siguiente Series, observar qué devuelve `values` e `index` e interpretar.

In [15]:
import pandas as pd
enteros = pd.Series([7,4,-5,3])
enteros

0    7
1    4
2   -5
3    3
dtype: int64

In [3]:
type(enteros.values)

numpy.ndarray

In [4]:
enteros.index # Por default, los índices van de 0 a N-1.

RangeIndex(start=0, stop=4, step=1)

Podemos asignar etiquetas (o índices) a cada valor de la serie.

In [5]:
reales = pd.Series([np.pi,0,-2,1.41], index = ["a", "b", "c", "d"])
display(reales)

a    3.141593
b    0.000000
c   -2.000000
d    1.410000
dtype: float64

In [6]:
display(reales.values)
display(reales.index)

array([ 3.14159265,  0.        , -2.        ,  1.41      ])

Index(['a', 'b', 'c', 'd'], dtype='object')

Para acceder a los elementos podemos usar las etiquetas.

In [7]:
print(reales["a"])

3.141592653589793

In [8]:
# Acceder por su posición no está recomendado. 
reales[1]

C:\Users\s94-e\AppData\Local\Temp\ipykernel_15532\2037761590.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  reales[1]

np.float64(0.0)

In [9]:
# Para acceder por su posición usamos iloc
reales.iloc[1]

np.float64(0.0)

In [10]:
# Podemos usar también rangos
reales.iloc[1:3]

b    0.0
c   -2.0
dtype: float64

In [11]:
# Para acceder por etiquetas podemos usar también loc
# Observar que para rangos de etiquetas sí incluye la última etiqueta
reales.loc["a":"c"]

a    3.141593
b    0.000000
c   -2.000000
dtype: float64

In [12]:
# Podemos definir labels numericos
temperaturas = pd.Series([15, 17, 18.2, 25], index = np.array([5, 10, 15, 20]))
print(temperaturas)

5     15.0
10    17.0
15    18.2
20    25.0
dtype: float64

In [13]:
# Que esperamos de los siguientes comandos?
print(temperaturas.iloc[1:3])
print(temperaturas.loc[10:20]) # Por qué??

10    17.0
15    18.2
dtype: float64
10    17.0
15    18.2
20    25.0
dtype: float64

In [14]:
# Funcionará?
temperaturas.iloc[10]

IndexError: single positional indexer is out-of-bounds

In [16]:
# Podemos seleccionar elementos mediante una lista de etiquetas
realesSub = reales[["a","b"]]
print(realesSub)
print(realesSub.index)

a    3.141593
b    0.000000
dtype: float64
Index(['a', 'b'], dtype='object')

## Operaciones con series
Las operaciones que pueden aplicarse a numpy arrays pueden aplicarse también a series de Pandas, conservando los índices.

In [17]:
reales

a    3.141593
b    0.000000
c   -2.000000
d    1.410000
dtype: float64

In [18]:
np.exp(reales)

a    23.140693
b     1.000000
c     0.135335
d     4.095955
dtype: float64

In [19]:
reales * 3

a    9.424778
b    0.000000
c   -6.000000
d    4.230000
dtype: float64

In [20]:
reales > 1

a     True
b    False
c    False
d     True
dtype: bool

In [21]:
reales[reales > 1]

a    3.141593
d    1.410000
dtype: float64

¿Qué esperamos que dé este código?

In [22]:
print(enteros)
print(reales)

0    7
1    4
2   -5
3    3
dtype: int64
a    3.141593
b    0.000000
c   -2.000000
d    1.410000
dtype: float64

In [23]:
enteros + reales

0   NaN
1   NaN
2   NaN
3   NaN
a   NaN
b   NaN
c   NaN
d   NaN
dtype: float64

NaN significa "not a number", se utiliza en series de Pandas para valores faltantes (missing values).

In [24]:
# Y ahora?
enteros2 = pd.Series([1,2,3,4], index = ["d", "b", "y", "z"])
enteros2

d    1
b    2
y    3
z    4
dtype: int64

In [25]:
suma = reales + enteros2
suma

a     NaN
b    2.00
c     NaN
d    2.41
y     NaN
z     NaN
dtype: float64

Vemos que solo se suman aparecen valores en las filas con índices que aparecen en las dos series.

In [26]:
# Los floats de Numyp aceptan el valor np.nan. 
# Qué resultados esperamos?
print(3 + np.nan)
print(0 * np.nan)
print(np.nan - np.nan)

nan
nan
nan

Las series de Pandas tienen varias funciones útiles que iremos viendo más adelante. A modo de ejemplo, interpretar qué hacen las siguientes funciones.

In [27]:
series1 = pd.Series(["a", "b", "c", "b", "a", "c", "x"])
series1

0    a
1    b
2    c
3    b
4    a
5    c
6    x
dtype: object

In [28]:
series1.isin(["b", "c"])

0    False
1     True
2     True
3     True
4    False
5     True
6    False
dtype: bool

In [29]:
# Qué hace este método?
series1.value_counts()

a    2
b    2
c    2
x    1
Name: count, dtype: int64

In [30]:
# Ejercicio: cómo me quedo solo con las filas con etiquetas "b" o "c"?

### DataFrames
Un data frame es una representación de los datos en formato de tabla en la que cada
columna son vectores del mismo tamaño. Como cada columna es un vector, cada columna puede
contener datos de un único tipo. Se pueden pensar como variables. Cada variable corresponde a una
serie de Pandas, y **todas las series de un dataframe están indexadas por los mismos índices**.

Una forma de crear un data frame es utilizando un "diccionario". Todas las variables del
diccionario deben ser vectores o listas de la misma longitud.

In [31]:
data = {"nombres": ["Rodrigo", "Sergio", "Cristina", "Diana"], "altura": np.array([178, 172, 175, 168]), "peso": np.array
([81.2, 76.1, 68.5, 64.0])}
display(data)

{'nombres': ['Rodrigo', 'Sergio', 'Cristina', 'Diana'],
 'altura': array([178, 172, 175, 168]),
 'peso': array([81.2, 76.1, 68.5, 64. ])}

In [32]:
type(data)

dict

In [33]:
data["peso"]

array([81.2, 76.1, 68.5, 64. ])

In [34]:
# Creamos un data frame con esos datos. Cuáles son los índices?
pacientes = pd.DataFrame(data)
pacientes

    nombres  altura  peso
0   Rodrigo     178  81.2
1    Sergio     172  76.1
2  Cristina     175  68.5
3     Diana     168  64.0

In [35]:
# En este ejemplo podemos usar los nombres como índices
pacientes = pd.DataFrame(data).set_index("nombres")
display(pacientes)

          altura  peso
nombres
Rodrigo      178  81.2
Sergio       172  76.1
Cristina     175  68.5
Diana        168  64.0

In [36]:
# Podemos acceder a las columnas de dos formas distintas
alturas = pacientes["altura"]
alturas

nombres
Rodrigo     178
Sergio      172
Cristina    175
Diana       168
Name: altura, dtype: int64

In [37]:
# Esto a veces es más práctico, pero hay que tener cuidado que el nombre usado no tenga otro significado o símbolos o espacios
pacientes.altura

nombres
Rodrigo     178
Sergio      172
Cristina    175
Diana       168
Name: altura, dtype: int64

In [38]:
type(alturas)

pandas.core.series.Series

In [39]:
alturas.dtype

dtype('int64')

A diferencia de las matrices en Numpy, un DataFrame de Pandas es un conjunto de columnas, no de filas. 
Si queremos saber la altura de Rodrigo, pensar cuál de los dos comandos será correcto antes de ejecutarlos.

In [40]:
pacientes["Rodrigo"].altura

KeyError: 'Rodrigo'

In [ ]:
pacientes["altura"].Rodrigo

Para acceder a una fila de un dataframe, podemos usar los métodos `loc[]` y `iloc[]`. 

¿Cómo se usan? ¿Cuál es la diferencia entre los dos comandos? ¿Que tipo de dato nos devuelve?

## Archivos de datos

La biblioteca Pandas nos permite trabajar fácilmente con archivos de datos.
1. Leer el archivo casos_coronavirus.csv .
2. Graficar la curva de casos por día.
3. Graficar la curva de casos acumulados.
4. Definir log_cum_casos como el logaritmo de la cantidad de casos acumulados y graficar en función de la cantidad de días transcurridos.
5. Estimar, tomando dos valores, la pendiente de la recta para los datos a partir del dia 30.
6. Graficar la recta estimada junto con los datos. ¿Consideran que es una buena estimación?

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("casos_coronavirus.csv") # DataFrame
df.head()  # Primeras filas del DataFrame

In [ ]:
# Información básica del DataFrame
df.info()

In [ ]:
# ¿Cómo usamos la fecha como índice?
df = pd.read_csv("casos_coronavirus.csv").set_index("fecha")
df

In [ ]:
# Graficamos utilizando el método plot de series de Pandas
df["confirmados_Nuevos"].plot()

In [ ]:
# Queremos graficar los casos acumulados, podemos usar el método cumsum() de series Pandas
df.confirmados_Nuevos.cumsum().plot()

**Ejercicio** 
Esta serie presenta un crecimiento exponencial. 
Queremos tomar logaritmos para linealizar, ¿como podemos hacerlo?

**Ejercicio.**

Esta serie presenta un crecimiento exponencial. Queremos tomar logaritmos para linealizar, ¿como podemos hacerlo?

Graficar los valores obtenidos.

In [ ]:
# Para combinar gráficos usamos plot de matplotlib.
casos = ???
plt.plot(casos)  # No es tan bueno para manejar los ticks de fechas

**Ejercicio.** Estimar la pendiente de la recta antes del confinamiento (dias 5 al 25) y la pendiente de la recta después del confinamiento. Graficas las rectas para verificar la estimación.

In [ ]:
casos = ???.reset_index(drop = True)  # Reseteamos índices para ver mejor el gráfico y estimar mejor la pendiente.
plt.plot(casos)

In [ ]:
casos = ???.reset_index(drop = True)  # Reseteamos índices para ver mejor el gráfico y estimar mejor la pendiente.
plt.plot(casos)  # No es tan bueno para manejar los ticks de fechas

# Agregamos la recta
x_recta = ???
y_recta = ???
plt.plot(x_recta, y_recta)

## Gapminder

A modo de ejemplo, vamos a explorar el dataset Gapminder que contiene datos poblacionales y de desarrollo humano de distintos países a lo largo del tiempo.

Si gapminder no está instalado, ejecutar el siguiente comando para instalarlo

In [ ]:
%pip install gapminder

In [ ]:
from gapminder import gapminder

Si les da un error de proxy al instalar paquetes, utilicen estos comandos para eliminar la configuración de proxy:

In [ ]:
# Ejecutar si no funcionó lo de arriba
#import os
#for k in ["HTTP_PROXY","HTTPS_PROXY","http_proxy","https_proxy"]:
#    os.environ.pop(k, None)

Si sigue sin funcionar, pueden descargar gapminder del sitio web:

In [ ]:
# Ejecutar si no funcionó lo de arriba
#url = "https://raw.githubusercontent.com/resbaz/r-novice-gapminder-files/master/data/gapminder-FiveYearData.csv"
#gapminder = pd.read_csv(url)

In [ ]:
# Verificamos si se cargo correctamente
display(gapminder)

**Pregunta:** Podemos usar alguna columna como índice?

In [ ]:
# Para ver las primeras cinco filas
gapminder.head()

Podemos ver información básica del DataFrame con la función info

In [ ]:
gapminder.info()

In [ ]:
# Vemos todos los países en la base
gapminder["country"].unique()

In [ ]:
# Cuántos países son?
gapminder["country"].nunique()

O podemos usar el atributo `size` de series de Pandas.

### Entrada en calor

1. Cuál era la población de Argentina en 1967? Y la de Brasil?
2. En qué países la expectativa de vida era mayor que 80 años en 2002? Y en 1997? (filtrar la tabla para dejar solo las filas correspondientes)

### groupby

In [ ]:
# Si queremos ver cuántos países hay en cada continente...
# podemos agregupar por continente y ver el tamaño de cada grupo
gapminder.groupby("continent").size()    # Para un dataframe agrupado, size es un método!

In [ ]:
# Pero cada país aparece varias veces, con datos de distintos años.
# Para contar sin repeticion usamos nuevamente nunique
cantidades = gapminder.groupby("continent")["country"].nunique()
cantidades

In [ ]:
# Que tipo de dato nos devolvió? Cómo está indexado?
cantidades["Africa"]

In [ ]:
# Si queremos calcular porcentajes, dividimos por la cantidad total de paises
totalPaises = gapminder["country"].nunique()
totalPaises
gapminder.groupby("continent")["country"].nunique() / totalPaises

### value_counts

In [ ]:
# O podemos usar el comando value_counts y pasarle un parámetro para que nos de los valores normalizados.
# (la normalización lleva la suma total a 1)
gapminder[["continent", "country"]].drop_duplicates().continent.value_counts(normalize=True)

In [ ]:
# Vemos todos los años disponibles
gapminder["year"].unique()

In [ ]:
# Tenemos datos de todos los países todos los años?
# Agrupamos los datos por año y calculamos el tamaño de cada bloque
gapminder.groupby("year").size()

In [ ]:
# Ejercicio: cómo podemos hacerlo utilizando value_counts?

In [ ]:
# Ejercicio: cómo podemos calcular la poblacion total por año

### Gráficos simples de funciones o puntos en el plano XY.
Vamos a graficar la población total mundial en función del año.

In [ ]:
pobAnual = gapminder.groupby("year")["pop"].sum()
type(pobAnual)

In [ ]:
pobAnual

In [ ]:
pobAnual.index

In [ ]:
# Opción 1
# Usamos la función plot de series de pandas
pobAnual.plot()

In [ ]:
# O podemos graficar solo puntos
pobAnual.plot(style = ".")

In [ ]:
# Opcion 3
# Asignamos los valores a variables (arrays de numpy) y graficamos las variables
x = pobAnual.index
y = pobAnual.values
plt.plot(x,y)

In [ ]:
# Opcion 4
# Matplotlib tiene una función scatter para graficar puntos
plt.scatter(x,y)

In [ ]:
# Vamos a analizar los datos de 2007
datos2007 = gapminder[gapminder["year"]==2007]

In [ ]:
# Queremos ver si hay relación entre el producto bruto y la expectativa de vida
plt.plot(datos2007.gdpPercap, datos2007.lifeExp)

In [ ]:
# Ay no, eso no, hacemos un "scatter plot"
plt.scatter(datos2007.gdpPercap, datos2007.lifeExp)
plt.show()

In [ ]:
# Se ve mejor la correlación si usamos escala logaritmica en el eje X
plt.scatter(datos2007.gdpPercap, datos2007.lifeExp)
plt.xscale('log')

Vamos a mejorar un poco el gráfico

In [ ]:
# Agregamos etiquetas al gráfico y a los ejes
plt.scatter(datos2007.gdpPercap, datos2007.lifeExp)
plt.xscale('log')
plt.xlabel('GDP per Capita [en USD]')
plt.ylabel('Expectativa de vida [en años]')
plt.title('Desarrollo Mundial en 2007')
plt.show()

Reemplacemos las marcas en el eje $x$ 10³, 10⁴, 10⁵ con 1k, 10k y 100k.

In [ ]:
plt.scatter(datos2007.gdpPercap, datos2007.lifeExp)
plt.xscale('log')
plt.xlabel('GDP per Capita [en USD]')
plt.ylabel('Expectativa de vida [en años]')
plt.title('Desarrollo Mundial en 2007')
plt.xticks([1000, 10000, 100000],['1k', '10k', '100k'])
plt.show()

Seaborn es una biblioteca para visualización de datos en Python, basada en Matplotlib que agrega muchas funcioanlidades.

In [ ]:
# Usamos scatterplot de seaborn para poder personalizar mejor el grafico

# Almacenamos la población como un array de numpy: np_pop
np_pop = np.array(datos2007["pop"])

sns.scatterplot(x = datos2007['gdpPercap'], y = datos2007['lifeExp'], hue = datos2007['continent'], size = np_pop*2, sizes=(20,400))
plt.grid(True)
plt.xscale('log')
plt.xlabel('GDP per Capita [en USD]')
plt.ylabel('Expectativa de vida [en años]')
plt.title('Desarrollo Mundial en 2007')
plt.xticks([1000, 10000, 100000],['1k', '10k', '100k'])
plt.show()

In [ ]:
# Aumenta el tamaño del gráfico
plt.figure(dpi=150)

# Alcenamos la población como un array de numpy: np_pop
np_pop = np.array(datos2007["pop"])
np_pop2 = np_pop*2
# Usamos scatterplot de seaborn para poder personalizar mejor el grafico
sns.scatterplot(x = datos2007['gdpPercap'], y = datos2007['lifeExp'], hue = datos2007['continent'], size = np_pop2, sizes=(20,400))
plt.grid(True)
plt.xscale('log')
plt.xlabel('GDP per Capita [en USD]')
plt.ylabel('Expectativa de vida [en años]')
plt.title('Desarrollo Mundial en 2007')
plt.xticks([1000, 10000, 100000],['1k', '10k', '100k'])
plt.show()

## Estadística descriptiva

In [ ]:
# Vamos a analizar los datos de 2007
datos2007 = gapminder[gapminder["year"]==2007]
datos2007

In [ ]:
# Queremos usar los países como índices
datos2007.set_index("country")

In [ ]:
# Funcionó?
datos2007

In [ ]:
# Para guardar los cambios, lo asignamos a la misma variable
datos2007 = datos2007.set_index("country")
datos2007

In [ ]:
# O usamos la opcion inplace = True
datos2007 = gapminder[gapminder["year"]==2007]
datos2007.set_index("country", inplace = True)
datos2007

In [ ]:
# O por último, hacemos todo en una sola linea (opcion recomendada)
datos2007 = gapminder[gapminder["year"]==2007].set_index("country")
datos2007

Mirando los datos de 2007, ¿cuál es el país con mayor expectativa de vida? ¿Cuál es el país con menor expectativa de vida?

En matemática, cuando queremos saber para qué valor se alcanza el máximo, decimos que queremos saber el "argumento" del máximo. Esta funcion suele llamarse `argmax`. Utilizar la función de numpy np.argmax para responder las preguntas.

La función de numpy devuelve la posición. Si queremos saber el índice, podemos usar el método de series de Panda idxmax().

### Medidas de tendencia central

Para el año 2007, calcular el valor medio y la mediana de las variables gdpPercap y lifeExp entre todos los países.
Son similares o distintas? A qué lo atribuyen? Consideran que alguna resume mejor la realidad que la otra?

In [ ]:
datos2007["lifeExp"].median()

In [ ]:
datos2007["lifeExp"].mean()

In [ ]:
datos2007["gdpPercap"].median()

In [ ]:
datos2007["gdpPercap"].mean()

¿Es lo mismo el promedio de la expectativa de vida entre todos los países y el promedio de la expectativa de vida entre todas las personas?
¿Cuál calculamos arriba? ¿Cómo podemos calcular el otro?

### Medidas de dispersión

Para el año 2007, calcular la varianza y el desvío estándar de las variables gdpPercap y lifeExp entre todos los países. ¿Cuál es más fácil de interpretar?

In [ ]:
datos2007["lifeExp"].var()

In [ ]:
datos2007["lifeExp"].std()